baseURL = "https://nigdaemon.github.io/"
title = "XT Weblog"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
summaryLength = 80
theme = "PaperMod"

[pagination]
  pagerSize = 100

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"


[params]
  author = "XT"
  mainSections = ["posts"]
  description = "XT的网络日志"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowWordCount = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hideSummary = true

  [params.label]
    text = "XT Weblog"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.35
    minMatchCharLength = 1
    keys = ["title", "permalink", "summary", "content"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
